In [5]:
import pandas as pd

# Simulating existing CUSTOMERS table with additional columns
customers_data = {
    'customer_id': [1, 2],
    'name': ['John Doe', 'Jane Smith'],
    'address': ['123 Elm St', '456 Oak St'],
    'email': ['john@example.com', 'jane@example.com']
}

# Add 30 more columns
for i in range(1, 31):
    customers_data[f'attribute_{i}'] = [f'Value{i}_1', f'Value{i}_2']

customers = pd.DataFrame(customers_data)

print('CUSTOMERS OG:\n')
print( customers)

# Simulating new S_CUSTOMERS data with 30+ columns, REC_STS, and REC_TMSTP
s_customers_data = {
    'customer_id': [1, 3],  # customer_id 1 exists, 3 is new
    'name': ['John Doe Updated', 'Sam Green'],
    'address': ['123 Elm St', '789 Pine St'],
    'email': ['john.updated@example.com', 'sam@example.com'],
    'rec_sts': ['ACTIVE', 'ACTIVE'],
    'rec_tmstp': ['2023-10-01 10:00:00', '2023-10-01 11:00:00']
}

# Add 30 more columns
for i in range(1, 31):
    s_customers_data[f'attribute_{i}'] = [f'NewValue{i}_1', f'NewValue{i}_2']

s_customers = pd.DataFrame(s_customers_data)
s_customers['rec_tmstp'] = pd.to_datetime(s_customers['rec_tmstp'])

# Filter only active records from S_CUSTOMERS
active_s_customers = s_customers[s_customers['rec_sts'] == 'ACTIVE']

# Merge the active_s_customers dataframe with customers dataframe on 'customer_id'
merged = active_s_customers.merge(customers, on='customer_id', suffixes=('_new', '_old'), how='left')

for index, row in merged.iterrows():
    if pd.notnull(row['name_old']):  # Existing record
        # Check if any column has changed dynamically
        changes = False
        update_columns = []
        for column in s_customers.columns:
            if column not in ['customer_id', 'rec_sts', 'rec_tmstp']:
                new_col = column + '_new'
                old_col = column + '_old'
                if row[new_col] != row[old_col]:
                    changes = True
                    update_columns.append(column)
        
        if changes:
            # Update the existing record in the CUSTOMERS table
            for column in update_columns:
                customers.loc[customers['customer_id'] == row['customer_id'], column] = row[column + '_new']
    else:  # New record, insert into CUSTOMERS
        new_record = {
            'customer_id': row['customer_id'],
            'name': row['name_new'],
            'address': row['address_new'],
            'email': row['email_new']
        }
        for column in s_customers.columns:
            if column not in ['customer_id', 'rec_sts', 'rec_tmstp']:
                new_record[column] = row[column + '_new']
        
        new_record_df = pd.DataFrame([new_record])
        customers = pd.concat([customers, new_record_df], ignore_index=True)
print('CUSTOMERS NEW/CHANGED:\n')
print(customers)

CUSTOMERS OG:

   customer_id        name     address             email attribute_1  \
0            1    John Doe  123 Elm St  john@example.com    Value1_1
1            2  Jane Smith  456 Oak St  jane@example.com    Value1_2

  attribute_2 attribute_3 attribute_4 attribute_5 attribute_6  ...  \
0    Value2_1    Value3_1    Value4_1    Value5_1    Value6_1  ...
1    Value2_2    Value3_2    Value4_2    Value5_2    Value6_2  ...

  attribute_21 attribute_22 attribute_23 attribute_24 attribute_25  \
0    Value21_1    Value22_1    Value23_1    Value24_1    Value25_1
1    Value21_2    Value22_2    Value23_2    Value24_2    Value25_2

  attribute_26 attribute_27 attribute_28 attribute_29 attribute_30
0    Value26_1    Value27_1    Value28_1    Value29_1    Value30_1
1    Value26_2    Value27_2    Value28_2    Value29_2    Value30_2

[2 rows x 34 columns]
CUSTOMERS NEW/CHANGED:

   customer_id              name      address                     email  \
0            1  John Doe Updated   123 Elm St  john.updated@example.com
1            2        Jane Smith   456 Oak St          jane@example.com
2            3         Sam Green  789 Pine St           sam@example.com

   attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0  NewValue1_1  NewValue2_1  NewValue3_1  NewValue4_1  NewValue5_1
1     Value1_2     Value2_2     Value3_2     Value4_2     Value5_2
2  NewValue1_2  NewValue2_2  NewValue3_2  NewValue4_2  NewValue5_2

   attribute_6  ...  attribute_21  attribute_22  attribute_23  attribute_24  \
0  NewValue6_1  ...  NewValue21_1  NewValue22_1  NewValue23_1  NewValue24_1
1     Value6_2  ...     Value21_2     Value22_2     Value23_2     Value24_2
2  NewValue6_2  ...  NewValue21_2  NewValue22_2  NewValue23_2  NewValue24_2

   attribute_25  attribute_26  attribute_27  attribute_28  attribute_29  \
0  NewValue25_1  NewValue26_1  NewValue27_1  NewValue28_1  NewValue29_1
1     Value25_2     Value26_2     Value27_2     Value28_2     Value29_2
2  NewValue25_2  NewValue26_2  NewValue27_2  NewValue28_2  NewValue29_2

   attribute_30
0  NewValue30_1
1     Value30_2
2  NewValue30_2

[3 rows x 34 columns]